### ISSUE TITLE
Issue with .compress animation

### ISSUE THREAD

**Issue by jminutaglio** [SimformSolutionsPvtLtd/SSCustomSideMenu#1]
hi - thank you for making this excellent project!

I'm having an issue with the compress option.  it doesn't show the screen image.

```
iOS 13.4.1
Xcode Version 11.4.1 (11E503a)
iPhone 11 (simulator)
```

`private func configureSideMenu() {
        
        self.menuTable.backgroundColor = .clear
        menuTable.separatorStyle = .none
        menuTable.rowHeight = 60
        menuTable.showsHorizontalScrollIndicator = false
        menuTable.showsVerticalScrollIndicator = false
        
        let menuCellConfig = SSMenuCellConfig()
        
        menuCellConfig.cellStyle = .defaultStyle // .customStyle
        menuCellConfig.leftIconPadding = 20
        menuCellConfig.imageToTitlePadding = 10
        menuCellConfig.imageHeight = 24
        menuCellConfig.imageWidth = 24
        
        menuCellConfig.selectedColor = .purple
        menuCellConfig.nonSelectedColor = .label
        
        menuCellConfig.images = [UIImage(named: "first"), UIImage(named: "second"), UIImage(named: "third"), UIImage(named: "logout")]
        menuCellConfig.titles = ["Home", "My Friends", "Settings", "Logout"]
        
        menuCellConfig.numberOfOptions = 4
        menuTable.config = menuCellConfig
        
        let sideMenuConfig = SSSideMenuConfig()
        sideMenuConfig.animationType = .compress(0.8, 20) // .slideIn, .compress(0.8, 20), .slideOut
        sideMenuConfig.sideMenuPlacement = .left // .right, .left
        sideMenuConfig.menuWidth = UIScreen.main.bounds.width * 0.5
        
        let firstViewController = storyboard?.instantiateViewController(withIdentifier: "ViewControllerAbout")
        let secondViewController = storyboard?.instantiateViewController(withIdentifier: "ViewController")
        
        
        sideMenuConfig.viewControllers = [firstViewController!, secondViewController!]
        
        sideMenuConfig.menuTable = menuTable
        self.ssMenuConfig = sideMenuConfig
        
        self.sideMenuDelegate = self
    }`

The above code shows a menu, but with a black screen, no image of the underlying screen.

Any ideas?

**Comment by YagnikBavishi04** [comment]
This code work perfectly in this demo could you please refer it again. Let me know if still facing any issue.  
[SSCustomSideMenu-master .zip](https://github.com/SimformSolutionsPvtLtd/SSCustomSideMenu/files/12853485/SSCustomSideMenu-master.zip)
