### ISSUE TITLE
Show menu slide out on the front

### ISSUE THREAD

**Issue by mirza4jobs** [SimformSolutionsPvtLtd/SSCustomSideMenu#2]
Hi, 
I am having an issue when I am trying to open the menu on the front view controller which is not part of the view controllers array of sideMenuConfig.

is there any way I can open the menu on the viewController class that is not part of sideMenuConfig?

**Comment by YagnikBavishi04** [comment]
Yes, you can access the side menu in any viewController class that is not part of sideMenuConfig using **SSSideMenuControls. openOrCloseSideMenu()**.
